apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp
  labels:
    name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp 
    spec:
      containers:
        - name: covid19
          image: prraneth2812/covidimage:latest
