apiVersion: v1 
kind: Service
metadata:
  name: newapp
  labels:
    name: newservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
      name: myapp
